### PR TITLE
Add script box height plugin

### PR DESCRIPTION
**Pull request by shepda**
**Add script box height plugin**

- Updated README.md
- Updated plugins.json

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Thanks for your contribution! Can you maybe add a note in the plugin's README about which Camunda Modeler version(s) this plugin support? This would help users a lot to clarify compatibility 👍 

Example: https://github.com/pinussilvestrus/camunda-modeler-autosave-plugin

image

**Comment by pinussilvestrus** [comment]
Can you please also update the commit message to fit the commit history?

```sh
chore: add script box height plugin
```

**Comment by shepda** [comment]
Hey thanks for your comments, I've made those changes.

**Review by pinussilvestrus — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
Thank you very much!

**Pull request merged**
