### PR TITLE
Add dmn-js Plugin

### PR DESCRIPTION
**Pull request by philippfromme**
* add dmn-js plugin
* update and improve other plugins
* fix and improve README

### CODE REVIEW

**Comment by philippfromme** [comment]
We have to decide whether we want to release a stable version of `camunda-modeler-plugin-helpers` before we add the dmn-js example.

**Comment by nikku** [comment]
> We have to decide whether we want to release a stable version of camunda-modeler-plugin-helpers before we add the dmn-js example.

What is our decision :eyes:?

**Comment by philippfromme** [comment]
Alright, so let's merge this and release a v3.4.0 of the helpers when appropriate.

**Comment by nikku** [comment]
Looks good.

**Pull request merged**
